### ISSUE TITLE
Server does not start

### ISSUE THREAD

**Issue by Dev-Mikko** [edumeet/edumeet-room-server#1]
Hi. I've tried to install the new server version but, when I try to launch it, I receive the following error:

![immagine](https://user-images.githubusercontent.com/35871747/198883009-90bc1012-7756-4708-9e5b-6e49557fde3b.png)

First of all, I copied the ```config.example.js``` in ```config.js``` file. Then I changed the configuration. Lastly, I installed all the needed packages using ```yarn install``` and used ```DEBUG=edumeet-room-server:* yarn start``` for running the server. I've also tried to use the ```yarn start``` command, but I've had the same error.

Do you have any suggestion on how to solve this problem? Thank you very much for the help.

**Comment by havfo** [comment]
What version of node are you running? Upgrade to at least 16.

**Comment by Dev-Mikko** [comment]
Problem solved. I had an old version of Node.js. Thank you @havfo .
