### ISSUE TITLE
Router.pipeToRouter() huge function

### ISSUE THREAD

**Issue by pnts-se** [edumeet/edumeet-room-server#16]
I was struggling while writing tests for `Router.pipeToRouter()`.
It's a 200+ line function with a lot of branches.

I suggest creating a `PipeTransportFactory` class being responsible for creating the pipe.
In the factory class we could create smaller private methods to reduce the length and complexity of the function.

We could pass the factory as argument to Router constructor.

**Comment by havfo** [comment]
The reason it is implemented like this is because it maps directly to the mediasoup API.

**Comment by pnts-se** [comment]
After discussing this on video meeting: let's try to stay as close as possible to Mediasoup terminology and code. Whatever benefit there would be to improve readibility and testability in room-server, it's more important to stay close to media-node and don't introduce discrepancies.

I'm closing this issue.
