### ISSUE TITLE
Client does not establish connection to mediaNode on reconnect

### ISSUE THREAD

**Issue by Dev-Mikko** [edumeet/edumeet-room-server#18]
Starting from this morning (after pulling all the changes), I have a problem with socket connection when a peer tries to join again in a (new) room after leaving.

Here, the console logs:

```shell
  edumeet-room-server:DEBUG:SocketIOConnection constructor() +154ms
  edumeet-room-server:DEBUG:SocketIOConnection handleSocket() +0ms
  edumeet-room-server:DEBUG:ServerManager handleConnection() [peerId: 36ae0ed3-deae-45c9-95c8-f1809d144a73, displayName: undefined, roomId: e0pfs2qx] +155ms
  edumeet-room-server:DEBUG:ServerManager handleConnection() there is already a Peer with same peerId [peerId: 36ae0ed3-deae-45c9-95c8-f1809d144a73] +0ms
  edumeet-room-server:WARN:socketHandler handleConnection() [error: Error: Invalid token at ServerManager.handleConnection (/home/devmikko/edumeet/edumeet-room-server/dist/src/ServerManager.js:49:23) at descriptor.value (/home/devmikko/edumeet/edumeet-room-server/node_modules/edumeet-common/lib/decorators.js:21:30) at Namespace.socketHandler (/home/devmikko/edumeet/edumeet-room-server/dist/src/common/socketHandler.js:15:23)     at Namespace.emit (node:events:513:28)     at Namespace.emit (node:domain:489:12) at Namespace.emitReserved (/home/devmikko/edumeet/edumeet-room-server/node_modules/socket.io/dist/typed-events.js:56:22) at /home/devmikko/edumeet/edumeet-room-server/node_modules/socket.io/dist/namespace.js:234:22     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)] +155ms
  edumeet-room-server:DEBUG:SocketIOConnection close() [id: iVohc0gDyRZlgSo0AAAJ] +1ms
  edumeet-room-server:DEBUG:SocketIOConnection socket disconnected +0ms
```

Any guess on how to solve this problem?

**Comment by pnts-se** [comment]
@Dev-Mikko I can reproduce it and will take a look.

**Comment by pnts-se** [comment]
The second time we join a room, room-server calls:
`peer.notify({method: 'roomReady'})`
but I don't think the client receives the socket message.

So the room-server has a representation of a room and a peer, but there's nothing on the media-node.
And the client does not call
`dispatch(joinRoom());`

I'll troubleshoot more later.

**Comment by pnts-se** [comment]
On L4, tcp socket for websocket is torn down when we leave the room from the client.
When trying to rejoin, a new tcp socket for websocket is established and client do indeed receive websocket messages.

Nothing is happening in the client-side SignalingService or RoomMiddleware though.

**Comment by Dev-Mikko** [comment]
Thank you so much for the reply @pnts-se. So it seems to be a client-side or media-node problem. Maybe it could be better to open an issue on client/media-node repo. What do you think about it?

**Comment by pnts-se** [comment]
@Dev-Mikko Might as well stay here. I guess we will have a lot of issues with the interaction between the various services, e.g. client and room-server. It might be hard to tell where the fault is, or it could be at both ends.

Let's just keep looking until we find what's wrong.

**Comment by Dev-Mikko** [comment]
OK, thank you again @pnts-se

**Comment by pnts-se** [comment]
I tried commenting out `signalingService.close();` - called in edumeet-client - when we leave the room. 
Then, the `SignalingService` is still available when we're joining the second time.
But the peer is still left in `serverManager.peers` on the room-server.
If I delete the peer manually on the room-server, then the client joins a second time, using `SignalingService`.

So right now, I consider the problem being that `SignalingService` is not setup on the client side when connecting a second time.

**Comment by havfo** [comment]
Fixed in https://github.com/edumeet/edumeet-client/pull/54
