### ISSUE TITLE
Multiple Edumeet Room Servers with load balancer

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet-room-server#21]
Dear Team,

I have been testing by deploying multiple room servers with load balancer, however when users connected they get into different sessions but not in same session.
I don't see configuration for redis in room server to manage this

Thanks
Alex

**Comment by havfo** [comment]
There is no communication between room-servers, so you need to make sure that all users in the same room end up on the same room-server. This can be done with ex. HAProxy stick tables or similar..

**Comment by Alex-YddeR** [comment]
ok, how about media-nodes can different users can connect to different media-node and can be same session. Because when i tested i see multiple users connected to different media-node and they are in same session.

**Comment by havfo** [comment]
That is correct, any user can be on any media-node and media will be piped between them. A note there though, at the moment, the load balancing between media-node is not done yet, and is simply round-robin.

**Comment by pnts-se** [comment]
@Alex-YddeR I am in the process of setting up multiple room-servers with HAProxy in front, and will be facing the same challenges. Perhaps we could convert this to a discussion and share our findings and results?
