### ISSUE TITLE
Load balancing of peers across media nodes

### ISSUE THREAD

**Issue by pnts-se** [edumeet/edumeet-room-server#22]
Currently load balancing of peers across media nodes is round robin.
We need to add a more suitable logic for this.

This has been discussed:
1. Keep a meeting on a single media node as long as possible
2. Add geographical closeness to media node to load balancing algorithm. Here we need to consider a suitable weight.

**Comment by Alex-YddeR** [comment]
May be we can add as following 

1. last-used:
2. least-used:
3. most-used:
4. round-robin: 
5. randomly-pick
6. Geographical Location based

**Comment by pnts-se** [comment]
@Alex-YddeR I'm currently working in the load balancing feature. It's on the `feat-lba` branch.

On a meeting with me, @havfo  and @so010 we talked about starting with the following LBA when a peer is joining a meeting. 

We will have a default sticky strategy to make the meeting stay on the same media-node as long as possible. Then organizations could choose which other LB strategies to use. I will add the geo strategy which will consider the geographical distance between client and the available media nodes.

1. Is the room active on any media-node? If not, choose the media-node that is closest to the client
2. If the meeting is active on a media-node, is it closer than 2000km to the client? If so join it. If not, pick the closest media-node to the client, if there are any media-node available that is closer. The geo distance threshold should be configurable.

**Comment by pnts-se** [comment]
Branch `feat-lba` is live at https://staging.edumeet.nordu.net

This is behind haproxy, so we try to create GeoPosition twice.
The second time we're using x-forwarded-for header and it works.

```
2023-02-23T10:18:56.468Z edumeet-room-server:DEBUG:GeoPosition create() [address: 10.244.2.0]
2023-02-23T10:18:56.468Z edumeet-room-server:DEBUG:GeoPosition create() [address: 155.4.132.192]
```
