### ISSUE TITLE
Use enum instead of string in permittedProducer

### ISSUE THREAD

**Issue by pnts-se** [edumeet/edumeet-room-server#6]
https://github.com/edumeet/edumeet-room-server/blob/1f27c4b7993b9b5e0277229dcce6ca073f8dc19d/src/common/authorization.ts#L177-L181

We should probably be using enum here instead of strings.
Perhaps `SourceType` as argument and definition of `SourceType` enum somwhere in `edumeet-common`?

**Comment by havfo** [comment]
Sounds good to me :+1:

**Comment by pnts-se** [comment]
Ok, I'll make it happen!
