### ISSUE TITLE
Unclear intent of isAllowedBecauseMissing

### ISSUE THREAD

**Issue by pnts-se** [edumeet/edumeet-room-server#7]
To me, the intent of this function is unclear.

https://github.com/edumeet/edumeet-room-server/blob/1f27c4b7993b9b5e0277229dcce6ca073f8dc19d/src/common/authorization.ts#L125-L133

A `Peer` is allowed to do something. 
Allowed to do what?
It's true if someone or something is missing.
Who/what is missing and from where?

It is called once from `Room` class when we're removing a `Peer`.
https://github.com/edumeet/edumeet-room-server/blob/1f27c4b7993b9b5e0277229dcce6ca073f8dc19d/src/Room.ts#L176-L178

Perhaps this could be refactored to make more sense when looking at it the first time?

**Comment by havfo** [comment]
You are right, it is not very clear what this does.

The purpose of the function is to check if, after that peer left, anyone is allowed to `PROMOTE_PEER`. It can happen that peer that left was the last peer that had that permission. If the option `allowWhenRoleMissing` has the `PROMOTE_PEER` permission in it, the rest of the peers will then get that.
